# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://www.raininggraces.com'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Raining Graces Birth Services
# Description of the Site
description: Birth Doula in Edmond & Oklahoma City Area
# URL of Image of the Site
site-image: /raininggraces/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Doula, Birth, Birthing, OKC, Oklahoma City, Edmond
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: "https://github.com/x3nc0n/raininggraces/blob/master/assets/images/field-flowers-sky.jpg?raw=true"

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: robin@raininggraces.com
facebook_username: robin.spaid
twitter_username: 
instagram_username: 
linkedin_username: 
github_username:  
youtube_channel_id:
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics:

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Robin Spaid
# URL for the Image of the Author
author-image: https://github.com/x3nc0n/raininggraces/blob/master/assets/images/robin_headshot.jpeg?raw=true
# 60 Words About the Author
author-about: Hello, my name is Robin Spaid, and I am a lifelong resident of Oklahoma City. My husband, John, and I have been married for 18 years. After our wedding I joined the Oklahoma City Police Department where I served our city for 7 years before becoming a stay-at-home mother to our growing family. We have been blessed with 6 beautiful children and 3 precious angels in Heaven. About a year ago I began answering God's call for me to support and encourage women as they journey into and through motherhood. Being a birth doula has been such an amazing gift. I have gained vast and valuable knowledge and skills through books, hands-on shadowing with a very experienced local doula, joined a mentorship program, and completed online courses from Spinning Babies. I look forward to empowering each woman to see her immense and incredible potential.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: 

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
